name: WsConnectionPlugin
version: '${version}'
main: ramune314159265.wsconnectionplugin.WsConnectionPlugin
api-version: '1.20'
load: STARTUP
authors: [ramune314159265]
description: ws Connection for Spigot
